#usage: ansible-playbook -i inventory.ini playbook3.yaml --ask-become-pass
- name: iotop i glances
  hosts: hosts
  become: true
  tasks:
     - name: Install iotop
       apt:
        name: iotop
        state: present

     - name: Install glances
       apt:
        name: glances
        state: present
        autoremove: yes
        autoclean: yes
