---
- name: Aplicar rol de instalación de software
  hosts: rocky
  become: yes
  roles:
    - role: warewulf
  vars:
    yum_packages:
      - kea
      - bind
      - tftp-server
    services:
      - { name: 'kea-dhcp4', src: 'roles/warewulf/confFiles/kea-dhcp4.conf.j2', dest: '/etc/kea/kea-dhcp4.conf', enabled: true }