---
#- name: Aplicar rol de instalación de software
#  hosts: rocky
#  become: yes
#  roles:
#    - role: warewulf
#  vars:
#    make_hosts: false
#    firewall_warewulf: true
#    monitoring_warewulf: false
#    install_yum: false
#    install_dnf: true
#    install_apt: false
#    install_pip: false
#    install_warewulf: true
#    dnf_packages: "{{ basic_packages }}"
#    services:
#      - name: lldpd
#        enabled: true

- name: Configurar sistema
  hosts: rocky
  become: yes
  tasks:
    - name: Enable powertools repository
      command: dnf config-manager --set-enabled powertools
      when: ansible_os_family == "RedHat"

    - name: Install EPEL release
      command: dnf install -y epel-release
      when: ansible_os_family == "RedHat"

    - name: Enable and start lldpd service
      systemd:
        name: lldpd
        enabled: yes
        state: started
      when: ansible_os_family == "RedHat"

    - name: Stop firewalld service
      systemd:
        name: firewalld
        state: stopped

    - name: Disable firewalld service
      systemd:
        name: firewalld
        enabled: no

    - name: Flush all iptables rules
      command: iptables -F

    - name: Flush all iptables NAT rules
      command: iptables -t nat -F

- name: Aplicar rol firewall
  hosts: rocky
  become: yes
  roles:
    - role: firewall
  vars:
    firewall_rules:
      - table: nat
        chain: POSTROUTING
        rule: "-o enp0s3 -j MASQUERADE"
      - table: filter
        chain: FORWARD
        rule: "-i enp0s8 -o enp0s3 -j ACCEPT"
      - table: filter
        chain: FORWARD
        rule: "-i enp0s8 -o enp0s3 -m state --state RELATED,ESTABLISHED -j ACCEPT"