---
- name: Aplicar instalación de software
  hosts: rocky
  become: yes
  roles:
    - role: warewulf
  vars:
    make_hosts: true
    monitoring_warewulf: false
    install_dnf: true
    dnf_packages: "{{ basic_packages }}"
    services:
      - name: lldpd
        enabled: true

- name: Configurar sistema
  hosts: rocky
  become: yes
  vars:
    make_hosts: true
  tasks:
    - name: Enable powertools repository
      command: dnf config-manager --set-enabled powertools
      when: ansible_os_family == "RedHat"

    - name: Install EPEL release
      command: dnf install -y epel-release
      when: ansible_os_family == "RedHat"

    - name: Enable and start lldpd service
      systemd:
        name: lldpd
        enabled: yes
        state: started
      when: ansible_os_family == "RedHat"

    - name: Stop and disable firewalld-libvirtd-nftables services
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
        - firewalld
        - libvirtd
        - nftables
      ignore_errors: yes

    - name: Flush all iptables rules
      command: iptables -F

    - name: Flush all iptables NAT rules
      command: iptables -t nat -F

    - name: Enable IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes

    - name: Ensure IP forwarding is persistent
      lineinfile:
        path: /etc/sysctl.conf
        regexp: '^net.ipv4.ip_forward'
        line: 'net.ipv4.ip_forward = 1'
        state: present

    - name: Apply masquerade rule to iptables
      iptables:
        table: nat
        chain: POSTROUTING
        out_interface: enp0s3
        jump: MASQUERADE

    - name: Enable and start iptables service
      systemd:
        name: iptables
        enabled: yes
        state: started
      when: ansible_os_family == "RedHat"

    - name: Move existing iptables configuration file
      command: mv /etc/sysconfig/iptables /etc/sysconfig/iptables.old
      ignore_errors: yes

    - name: Save current iptables rules
      command: service iptables save
      ignore_errors: yes

    - name: Configure Clustershell groups
      template:
        src: ./roles/warewulf/confFiles/local.cfg.j2
        dest: /etc/clustershell/groups.d/local.cfg
        owner: root
        group: root
        mode: '0644'
      when: ansible_os_family == "RedHat"

    - name: Set timezone to Europe/Madrid
      command: timedatectl set-timezone Europe/Madrid

    - name: Apply chrony configuration template
      template:
        src: ./roles/warewulf/confFiles/chrony.conf.j2
        dest: /etc/chrony.conf
        owner: root
        group: root
        mode: '0644'

    - name: Enable and start chronyd service
      systemd:
        name: chronyd
        enabled: yes
        state: restarted

    - name: Disable SELinux
      command: sed -i 's/\(^SELINUX=\).*/\1disabled/g' /etc/selinux/config

    - name: Create directory for OS updates
      file:
        path: /install/osupdates/rocky8/x86_64/
        state: directory
        mode: '0755'

    - name: Sync repositories
      vars:
        sync: true
      block:
        - name: Sync AppStream repository
          command: dnf reposync -n --repoid=appstream --download-path=/install/osupdates/rocky8/x86_64 --downloadcomps --download-metadata --gpgcheck
        - name: Sync BaseOS repository
          command: dnf reposync -n --repoid=baseos --download-path=/install/osupdates/rocky8/x86_64 --downloadcomps --download-metadata --gpgcheck

        - name: Sync EPEL repository
          command: dnf reposync -n --repoid=epel --download-path=/install/osupdates/rhels8/x86_64 --downloadcomps --download-metadata --gpgcheck

        - name: Sync EPEL Modular repository
          command: dnf reposync -n --repoid=epel --download-path=/install/osupdates/rocky8/x86_64 --downloadcomps --download-metadata --gpgcheck

        - name: Sync CodeReady repository
          command: dnf reposync -n --repoid=codeready --download-path=/install/osupdates/rhels8/x86_64 --downloadcomps --download-metadata --gpgcheck

        - name: Mv AppStream repository
          command: mv /install/osupdates/rhels8/x86_64/rhel-8-for-x86_64-appstream-rpms /install/osupdates/rhels8/x86_64/appstream

        - name: Mv BaseOS repository
          command: mv /install/osupdates/rhels8/x86_64/rhel-8-for-x86_64-baseos-rpms /install/osupdates/rhels8/x86_64/baseos

        - name: Mv CodeReady repository
          command: mv /install/osupdates/rhels8/x86_64/codeready-builder-for-rhel-8-x86_64-rpms /install/osupdates/rhels8/x86_64/codeready-builder
      when: sync == true


    - name: Disable user directories web configuration
      command: mv /etc/httpd/conf.d/userdir.conf /etc/httpd/conf.d/userdir.conf.disabled
      when: ansible_os_family == "RedHat"

    - name: Disable welcome page configuration
      command: mv /etc/httpd/conf.d/welcome.conf /etc/httpd/conf.d/welcome.conf.disabled
      when: ansible_os_family == "RedHat"

    - name: Configurar VirtualHost por defecto
      vars:
        server_name: "192.168.1.1"
        server_alias: "headnode.hpc.domain"
      block:
        - name: Aplicar plantilla de VirtualHost
          template:
            src: templates/000-default.conf.j2
            dest: /etc/httpd/conf.d/000-default.conf
            owner: root
            group: root
            mode: '0644'
        - name: Reiniciar servicio httpd
          systemd:
            name: httpd
            state: restarted


