---
- name: Aplicar rol de instalación de software
  hosts: rocky
  become: yes
  roles:
    - role: warewulf
  vars:
    make_hosts: false
    firewall_warewulf: true
    monitoring_warewulf: false
    install_yum: false
    install_dnf: true
    install_apt: false
    install_pip: false
    install_warewulf: true
    dnf_packages: "{{ basic_packages }}"
    services:
      - name: lldpd
        enabled: true

- name: Configurar sistema
  hosts: rocky
  become: yes
  tasks:
    - name: Enable powertools repository
      command: dnf config-manager --set-enabled powertools
      when: ansible_os_family == "RedHat" and ansible_distribution_version | version_compare('8', 'ge') and package_manager == "dnf"

    - name: Install EPEL release
      command: dnf install -y epel-release
      when: ansible_os_family == "RedHat" and ansible_distribution_version | version_compare('8', 'ge') and package_manager == "dnf"

    - name: Enable and start lldpd service
      systemd:
        name: lldpd
        enabled: yes
        state: started
      when: ansible_os_family == "RedHat" and install_packages

    - name: Stop firewalld service
      systemd:
        name: firewalld
        state: stopped
      when: install_packages

    - name: Disable firewalld service
      systemd:
        name: firewalld
        enabled: no
      when: install_packages

    - name: Flush all iptables rules
      command: iptables -F
      when: install_packages

    - name: Flush all iptables NAT rules
      command: iptables -t nat -F
      when: install_packages

- name: Aplicar rol firewall
  hosts: rocky
  become: yes
  roles:
    - role: firewall
  vars:
    firewall_rules:
      - table: nat
        chain: POSTROUTING
        rule: "-o <external-if> -j MASQUERADE"
      - table: filter
        chain: FORWARD
        rule: "-i <internal-if> -o <external-if> -j ACCEPT"
      - table: filter
        chain: FORWARD
        rule: "-i <internal-if> -o <external-if> -m state --state RELATED,ESTABLISHED -j ACCEPT"