---
- name: Aplicar rol de instalación de software
  hosts: localhost
  become: yes
  roles:
    - role: warewulf
  vars:
    yum_packages:
      - kea-dhcp4-server
      - bind9.16
      - tftp-server.x86_64
    services:
      - { name: 'kea-dhcp4', src: 'kea-dhcp4.conf.j2', dest: '/etc/kea/kea-dhcp4.conf', enabled: true }
      - { name: 'named', src: 'named.conf.options.j2', dest: '/etc/bind/named.conf.options', enabled: true }
      - { name: 'tftp', src: 'tftpd-hpa.j2', dest: '/etc/xinetd.d/tftp', enabled: true }
