---
# tasks file for openNebula


- name: Crear una red virtual
  command: onevnet create "{{ opennebula_vnet_template }}"
  become: yes
  when: opennebula_vnet_template is defined

- name: Crear un datastore
  command: onedatastore create "{{ opennebula_datastore_template }}"
  become: yes
  when: opennebula_datastore_template is defined

# tasks file for openNebula_monitoring



- name: Configurar escalabilidad automática
  command: onevm resize "{{ opennebula_vm_id }}" --cpu "{{ opennebula_cpu }}" --memory "{{ opennebula_memory }}"
  become: yes
  when: opennebula_vm_id is defined and opennebula_cpu is defined and opennebula_memory is defined