#Directory of vars for the usage of ansible playbooks
---
created_username: isard
copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
paquets: [ 'curl', 'glances', 'git', 'ufw']
