---
- name: Enable repositories
  hosts: rocky
  become: yes
  tasks:
    - name: Enable EPEL repository
      command: dnf install -y epel-release
      when: ansible_os_family == "RedHat"

    - name: Enable powertools repository
      command: dnf config-manager --set-enabled powertools
      when: ansible_os_family == "RedHat"