---
- name: Aplicar instalación de software
  hosts: rocky
  become: yes
  tasks:
  roles:
    - role: warewulf
  vars:
    make_hosts: true
    monitoring_warewulf: false
    install_dnf: true
    dnf_packages: "{{ basic_packages }}"
    services:
      - name: lldpd
        enabled: true