---
- name: Manage YUM repository files
  hosts: rocky
  become: yes
  tasks:
    - name: Create directory for online repos
      file:
        path: /etc/yum.repos.d/online-repos
        state: directory
        mode: '0755'

    - name: Check if any .repo files exist
      find:
        paths: /etc/yum.repos.d/
        patterns: '*.repo'
      register: repo_files

    - name: Copy .repo files to online-repos directory
      copy:
        src: "{{ item.path }}"
        dest: /etc/yum.repos.d/online-repos/
        mode: '0644'
      loop: "{{ repo_files.files }}"
      when: repo_files.matched > 0
      ignore_errors: yes