---
- name: Manage YUM local repository
  hosts: rocky
  become: yes
  tasks:
    - name: Set REPOSIP variable
      set_fact:
        repos_ip: "192.168.1.1"

    - name: Remove unnecessary repo files
      file:
        path: "/etc/yum.repos.d/{{ item }}"
        state: absent
      loop:
        - epel-testing*.repo
        - Rocky-Debuginfo.repo
        - Rocky-Devel.repo
        - Rocky-Media.repo
        - Rocky-NFV.repo
        - Rocky-Plus.repo
        - Rocky-ResilientStorage.repo
        - Rocky-RT.repo
        - Rocky-Sources.repo

    - name: Rename repo files
      shell: |
        for i in $(ls /etc/yum.repos.d/*.repo); do
          base=$(basename $i .repo)
          if [[ $base != *-local ]]; then
            mv /etc/yum.repos.d/$base.repo /etc/yum.repos.d/$base-local.repo
          fi
        done
      args:
        executable: /bin/bash

    - name: Update repo file names
      shell: |
        for file in /etc/yum.repos.d/*.repo; do
          if ! grep -q '\-local\]' "$file"; then
            sed -i 's/\]/-local\]/' "$file"
          fi
        done
      args:
        executable: /bin/bash

    - name: Update repo file descriptions
      shell: |
        for file in /etc/yum.repos.d/*.repo; do
          if ! grep -q ' - Local' "$file"; then
            sed -i '/name/s/$/ - Local/' "$file"
          fi
        done
      args:
        executable: /bin/bash

    - name: Comment out mirrorlist and metalink in Rocky repos
      shell: |
        for file in /etc/yum.repos.d/Rocky*.repo; do
          sed -i '/mirrorlist=/s/^/#/' "$file"
        done
      args:
        executable: /bin/bash

    - name: Comment out metalink in EPEL repos
      shell: |
        for file in /etc/yum.repos.d/epel*.repo; do
          sed -i '/metalink=/s/^/#/' "$file"
        done
      args:
        executable: /bin/bash

    - name: Backup and restore EPEL GPG key
      block:
        - name: Backup EPEL GPG key
          copy:
            src: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8
            dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8.bak

        - name: Remove EPEL release
          command: dnf remove -y epel-release

        - name: Restore EPEL GPG key
          copy:
            src: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8.bak
            dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8
            remote_src: yes

    - name: Find all .repo files
      find:
        paths: /etc/yum.repos.d/
        patterns: '*-local.repo'
      register: repo_files

    - name: Update baseurl in all local repo files
      shell: |
        for file in /etc/yum.repos.d/*-local.repo; do
          repo_name=$(basename $file .repo)
          case $repo_name in
            Rocky-AppStream-local)
              baseurl="http://192.168.1.1/install/osupdates/rocky8/x86_64/appstream"
              ;;
            Rocky-BaseOS-local)
              baseurl="http://192.168.1.1/install/osupdates/rocky8/x86_64/baseos"
              ;;
            Rocky-Extras-local)
              baseurl="http://192.168.1.1/install/osupdates/rocky8/x86_64/extras"
              ;;
            Rocky-HighAvailability-local)
              baseurl="http://192.168.1.1/install/osupdates/rocky8/x86_64/highavailability"
              ;;
            Rocky-PowerTools-local)
              baseurl="http://192.168.1.1/install/osupdates/rocky8/x86_64/powertools"
              ;;
            epel-local)
              baseurl="http://192.168.1.1/install/osupdates/rocky8/x86_64/epel"
              ;;
            epel-modular-local)
              baseurl="http://192.168.1.1/install/osupdates/rocky8/x86_64/epel-modular"
              ;;
            *)
              baseurl=""
              ;;
          esac
          if [ -n "$baseurl" ]; then
            sed -i "s|^#baseurl=.*$|baseurl=$baseurl|" "$file"
            sed -i "s|^baseurl=.*$|baseurl=$baseurl|" "$file"
          fi
        done