# Enable repositories
- name: Enable EPEL repository
  command: dnf install -y epel-release
  when: ansible_os_family == "RedHat"
  ignore_errors: yes

- name: Enable powertools repository
  command: dnf config-manager --set-enabled powertools
  when: ansible_os_family == "RedHat"
  ignore_errors: yes

- name: Aplicar instalación de software
  services:
    - name: lldpd # Enable and start lldpd service
      enabled: true

- name: Instalar paquetes con dnf
  dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ dnf_packages }}"
  when: ansible_os_family == "RedHat" and install_dnf == true
  ignore_errors: yes

- name: "Modify /etc/hosts"
  template:
    src: ../confFiles/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
  when: make_hosts == true

# Configurar sistema # Configure system settings
- name: Install EPEL release package
  command: dnf install -y epel-release
  when: ansible_os_family == "RedHat"

- name: Enable and start lldpd service
  systemd:
    name: lldpd
    enabled: yes
    state: started
  when: ansible_os_family == "RedHat"
