- name: Check if userdir.conf exists
  stat:
    path: /etc/httpd/conf.d/userdir.conf
  register: userdir_conf

- name: Disable user directories web configuration
  command: mv /etc/httpd/conf.d/userdir.conf /etc/httpd/conf.d/userdir.conf.disabled
  when: userdir_conf.stat.exists
  ignore_errors: yes

- name: Check if welcome.conf exists
  stat:
    path: /etc/httpd/conf.d/welcome.conf
  register: welcome_conf

- name: Disable welcome page configuration
  command: mv /etc/httpd/conf.d/welcome.conf /etc/httpd/conf.d/welcome.conf.disabled
  when: welcome_conf.stat.exists
  ignore_errors: yes

- name: Configure default VirtualHost
  vars:
    server_name: "{{ hnodeIP }}" # Use the head node internal network IP address
    server_alias: "{{ hnodeName }}" # Use the head node hostname
  block:
    - name: Apply default template to 000-default.conf
      template: # Apply the 000-default.conf.j2 template to the /etc/httpd/conf.d/000-default.conf file
        src: ../confFiles/000-default.conf.j2
        dest: /etc/httpd/conf.d/000-default.conf
        owner: root
        group: root
        mode: '0644'

- name: Enable and start Apache service
  hosts: rocky
  become: yes
  tasks:
    - name: Enable httpd service
      systemd:
        name: httpd
        enabled: yes
        state: started