---
# tasks file for warewulf
- name: "Instalar paquetes con dnf"
  dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ dnf_packages }}"
  when: ansible_os_family == "RedHat" and install_dnf == true
  ignore_errors: yes

- name: "Include monitoring role"
  include_role:
    name: monitoring
  when: monitoring_warewulf == true

# INCLUDES
- name: "Modify /etc/hosts"
  template:
    src: ./roles/warewulf/confFiles/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
  when: make_hosts == true
