# usage ansible-playbook -i inventory.ini playbook1.yaml
- name: Ping Echo
  hosts: all
  become: false
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
      msg: Hello world
