#usage ansible-playbook -i inventory.ini playbook8.yaml --ask-become-pass
- name: Activar apache2
  hosts: www
  become: yes
  tasks:
    - name: Instalar apache2 si no está instalado
      apt:
        name: apache2
        state: present

    - name: Activar apache2
      service:
        name: apache2
        state: started
        enabled: yes
