---
# vars file for warewulf
#BASIC packages
basic_packages:
  - iptables*
  - authselect
  - bash-completion
  - bind-utils
  - btop
  - byobu
  - bzip2
  - chrony
  - dmidecode
  - git
  - glibc-langpack-en
  - glibc-langpack-es
  - htop
  - iftop
  - iotop
  - iperf3
  - ipmitool
  - lldpd
  - lsof
  - mlocate
  - mtr
  - net-tools
  - nmap
  - rsync
  - rsyslog
  - sshpass
  - sysstat
  - tar
  - traceroute
  - telnet
  - texinfo
  - vim
  - wget
  - yum-utils
  - zip
  - xorg-x11-xauth
  - xorg-x11-fonts-*
  - xorg-x11-utils
  - clustershell
  - python3-clustershell
  - createrepo
  - dnf-utils
  - httpd