---
# vars file for warewulf
kea_interfaces: "enp2s0"
subnet1: "192.168.1.0/24"
pool1: "192.168.1.100 - 192.168.1.200"
router1: "192.168.1.1"
subnet2: "172.16.1.0/24"
pool2: "172.16.1.10 - 172.16.1.100"
router2: "172.16.1.1"
dns_servers: "192.168.1.2, 192.168.1.3"
domain_name: "hpc.test.es"
#BASIC packages
basic_packages:
  - iptables*
  - authselect
  - bash-completion
  - bind-utils
  - btop
  - byobu
  - bzip2
  - chrony
  - dmidecode
  - git
  - glibc-langpack-en
  - glibc-langpack-es
  - htop
  - iftop
  - iotop
  - iperf3
  - ipmitool
  - lldpd
  - lsof
  - mlocate
  - mtr
  - net-tools
  - nmap
  - rsync
  - rsyslog
  - sshpass
  - sysstat
  - tar
  - traceroute
  - telnet
  - texinfo
  - vim
  - wget
  - yum-utils
  - zip
  - xorg-x11-xauth
  - xorg-x11-fonts-*
  - xorg-x11-utils
  - clustershell
  - python3-clustershell
  - createrepo
  - dnf-utils
  - httpd