---
# vars file for warewulf
update_overlay: false
warewulf_images: false
sync: true
ipaddr: 172.16.1.10
netmask: 255.255.255.0
network: 172.16.1.0
hnodeIP: 172.16.1.10
#BASIC packages
basic_packages:
  - iptables*
  - authselect
  - bash-completion
  - bind-utils
  - btop
  - byobu
  - bzip2
  - chrony
  - dmidecode
  - git
  - glibc-langpack-en
  - glibc-langpack-es
  - htop
  - iftop
  - iotop
  - iperf3
  - ipmitool
  - lldpd
  - lsof
  - mlocate
  - mtr
  - net-tools
  - nmap
  - rsync
  - rsyslog
  - sshpass
  - sysstat
  - tar
  - traceroute
  - telnet
  - texinfo
  - vim
  - wget
  - yum-utils
  - zip
  - xorg-x11-xauth
  - xorg-x11-fonts-*
  - xorg-x11-utils
  - clustershell
  - python3-clustershell
  - createrepo
  - dnf-utils
  - httpd
warewulf_packages:
  - basesystem
  - bash
  - chkconfig
  - coreutils
  - cpio
  - cronie
  - crontabs
  - dhclient
  - e2fsprogs
  - ethtool
  - filesystem
  - findutils
  - initscripts
  - ipmitool
  - gawk
  - grep
  - gzip
  - initscripts
  - iproute
  - iputils
  - less
  - kernel-core
  - kernel-modules
  - net-tools
  - nfs-utils
  - network-scripts
  - openssh-clients
  - openssh-server
  - pam
  - parted
  - pciutils
  - psmisc
  - rsync
  - rsyslog
  - sed
  - setup
  - shadow-utils
  - strace
  - tar
  - tzdata
  - util-linux
  - vim
  - wget
  - which
  - words
  - xfsprogs
  - yum
  - zlib
  - zip
  - rocky-release